#!/usr/bin/env bash

factorize() {
    local num=$1
    local divisor=2

    while ((num > 1)); do
        if ((num % divisor == 0)); then
            echo "$num=$divisor*$(($num / $divisor))"
            return
        fi
        ((divisor++))
    done
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "File '$1' not found"
    exit 1
fi

while IFS= read -r line || [ -n "$line" ]; do
    re='^[0-9]+$'
    if ! [[ $line =~ $re ]]; then
        echo "Invalid input: '$line'"
        continue
    fi

    if ((line <= 1)); then
        echo "Number should be greater than 1: '$line'"
        continue
    fi

    factorize "$line"
done < "$1"
