#!/usr/bin/env bash

factorize() {
    local num=$1
    local divisor=2

    while ((num > 1)); do
        if ((num % divisor == 0)); then
            echo "$1=$divisor*$(($num / $divisor))"
            return
        fi
        ((divisor++))
    done
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r line; do
        factorize "$line"
    done < "$1"
fi
